version: "3.8"
services:
  app:
    build: .
    ports:
      - "4500:4500"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
